import { z } from 'zod';

export const b2bSimulatorSchema = z.object({
  // Profil client
  clientType: z.enum(['particulier', 'pro']),
  clientName: z.string().min(1, 'Le nom est requis'),
  clientEmail: z.string().email('Email invalide').min(1, 'L\'email est requis'),
  clientPhone: z.string().min(1, 'Le téléphone est requis'),
  clientAddress: z.string().min(1, 'L\'adresse est requise'),
  companyName: z.string().optional(),
  companySiret: z.string().optional(),
  region: z.string().min(1, 'La région est requise'),

  // Descriptif bien
  refDossier: z.string().optional(),
  propertyAddress: z.string().min(1, 'L\'adresse du bien est requise'),
  secteurQuartier: z.string().optional(),
  typeBien: z.string(),
  ancienOuNeuf: z.string(),
  prixAffiche: z.coerce.number().min(0, 'Doit être positif'),
  valeurApresTravaux: z.coerce.number().min(0, 'Doit être positif'),
  nbPieces: z.coerce.number().min(1),
  nbChambres: z.coerce.number().min(0),
  nbSdb: z.coerce.number().min(0),
  surfaceHabitable: z.coerce.number().min(1, 'Surface > 0 requise'),
  surfaceTerrain: z.coerce.number().min(0),
  terrasseBalcon: z.string(),
  piscine: z.string(),
  jardin: z.string(),
  garageParking: z.string(),
  ascenseur: z.string(),
  etage: z.string(),
  copropriete: z.string(),
  chargesCopro: z.coerce.number().min(0),
  taxeFonciere: z.coerce.number().min(0),
  environnement: z.string(),
  procheTransport: z.string(),
  procheCommerces: z.string(),
  procheEcoles: z.string(),
  prochePlage: z.string(),
  distanceCentre: z.string(),
  etatGeneral: z.string(),
  travauxPrevoir: z.string().optional(),
  montantTravaux: z.coerce.number().min(0),
  cuisineRefaire: z.string(),
  sdbRefaire: z.string(),
  elec: z.string(),
  plomberie: z.string(),
  toiture: z.string(),
  facade: z.string(),
  fenetres: z.string(),
  climatisation: z.string(),
  meuble: z.string(),
  locTouristique: z.string(),
  licenceTouristique: z.string(),
  rendementLocatif: z.coerce.number().min(0),
  commentaires: z.string().optional(),

  // Simulation
  prixAchat: z.coerce.number().min(0),
  travauxSim: z.coerce.number().min(0),
  honorairesPct: z.coerce.number().min(0),
  fraisAcquisitionPct: z.coerce.number().min(0),
  fraisReventePct: z.coerce.number().min(0),
  portageInterets: z.coerce.number().min(0),
  prixReventeEstime: z.coerce.number().min(0),
  impotPlusValuePct: z.coerce.number().min(0),
  dureeMois: z.coerce.number().min(1),
});

export type B2BSimulatorFormData = z.infer<typeof b2bSimulatorSchema>;

export const defaultB2BValues: B2BSimulatorFormData = {
  clientType: 'particulier',
  clientName: 'Jean Dupont',
  clientEmail: 'jean.dupont@email.com',
  clientPhone: '06 12 34 56 78',
  clientAddress: '10 Avenue des Champs-Élysées, 75008 Paris',
  companyName: 'Acme Corp',
  companySiret: '123 456 789 00010',
  region: 'Valence',
  
  refDossier: 'DOS-2023-001',
  propertyAddress: '12 rue des Fleurs, 26000 Valence',
  secteurQuartier: 'Centre-ville',
  typeBien: 'Appartement',
  ancienOuNeuf: 'Ancien',
  prixAffiche: 260000,
  valeurApresTravaux: 300000,
  nbPieces: 4,
  nbChambres: 2,
  nbSdb: 1,
  surfaceHabitable: 85,
  surfaceTerrain: 0,
  terrasseBalcon: 'Oui',
  piscine: 'Non',
  jardin: 'Non',
  garageParking: 'Oui',
  ascenseur: 'Oui',
  etage: '3',
  copropriete: 'Oui',
  chargesCopro: 1200,
  taxeFonciere: 900,
  environnement: 'Middle-City',
  procheTransport: 'Oui',
  procheCommerces: 'Oui',
  procheEcoles: 'Oui',
  prochePlage: 'Non',
  distanceCentre: '5 min',
  etatGeneral: 'Bon',
  travauxPrevoir: 'Rafraîchissement',
  montantTravaux: 15000,
  cuisineRefaire: 'Non',
  sdbRefaire: 'Non',
  elec: 'Aux normes',
  plomberie: 'Bon état',
  toiture: 'Bon état',
  facade: 'Bon état',
  fenetres: 'Double vitrage',
  climatisation: 'Non',
  meuble: 'Non',
  locTouristique: 'Possible',
  licenceTouristique: 'Non',
  rendementLocatif: 5.5,
  commentaires: '',

  prixAchat: 250000,
  travauxSim: 40000,
  honorairesPct: 6.05,
  fraisAcquisitionPct: 14,
  fraisReventePct: 5,
  portageInterets: 8000,
  prixReventeEstime: 420000,
  impotPlusValuePct: 19,
  dureeMois: 8,
};
